services:
  backend:
    build: backend
    container_name: fastapi_service
    depends_on:
      - db_postgres
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/backend

#  frontend:
#    build:
#      context: ./frontend
#    ports:
#      - "3000:3000"

  redis-cache:
    image: redis:alpine
    hostname: redis-cache
    container_name: redis-cache
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data

  db_postgres:
    image: postgres:14.3-alpine
    hostname: db_postgres
    container_name: db_postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_HOST=db_postgres
      - POSTGRES_PORT=5432
    expose:
      - 5432
    volumes:
      - db-postgres:/var/lib/postgresql/data

volumes:
  db-postgres:
    driver: local

  cache:
    driver: local